import {writeFileSync} from 'node:fs';
import {chromium} from '@playwright/test';import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome-stable',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
try{
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{localStorage.setItem('night-shift-campaign-v1',JSON.stringify({unlocked:3}));localStorage.setItem('night-shift-tutorial-v1',JSON.stringify(['move','key','box','flash','decoy','heal','door','exit']));});
 await page.goto((process.env.BASE_URL||'http://localhost:5174')+'/?playtest=encounters');await page.locator('#start:enabled').waitFor();await page.locator('[data-night="3"]').click();await page.locator('#start').click();await page.waitForFunction(()=>window.__nightshift?.().night===3&&window.__nightshift().weeper);
 assert.ok(await page.evaluate(()=>!!window.__nightshiftScene));
 const atlases=await page.evaluate(async()=>{const {registerHospitalPatient}=await import('/src/hospital-art.ts'),s=window.__nightshiftScene;return ['listener','light-shy','patroller'].map(kind=>{const key=registerHospitalPatient(s,kind),texture=s.textures.get(key);return {kind,frames:texture.frameTotal,image:texture.getSourceImage().toDataURL('image/png')};});});
 for(const atlas of atlases){assert.equal(atlas.frames,17);writeFileSync('/tmp/night-shift-'+atlas.kind+'-atlas.png',Buffer.from(atlas.image.split(',')[1],'base64'));}
 const decoded=await page.evaluate(async()=>{const tracks=await (await fetch('/game/music.json')).json(),ctx=new AudioContext();try{return await Promise.all(tracks.map(async track=>{const bytes=await (await fetch(track.opusFile)).arrayBuffer(),buffer=await ctx.decodeAudioData(bytes);return {id:track.id,duration:buffer.duration};}));}finally{await ctx.close();}});assert.equal(decoded.length,9);assert.ok(Math.abs(decoded.find(t=>t.id==='power').duration-8)<.15);

 const state=()=>page.evaluate(()=>window.__nightshift());
 await page.keyboard.press('t');await page.waitForFunction(()=>!window.__nightshift().flashlightOn);const off=await state();assert.equal(off.flashlightOn,false);await page.waitForTimeout(250);assert.equal((await state()).battery,off.battery);await page.locator('#flashlight-toggle').click();assert.equal((await state()).flashlightOn,true);await page.waitForTimeout(350);assert.ok((await state()).battery<off.battery);
 // Quiet approach must visibly change the rendered patient even with the beam off.
 await page.evaluate(()=>{const s=window.__nightshiftScene;s.cooldown=999;s.ghostTime=0;s.player.setPosition(415,318);s.weeper.position={x:535,y:318};s.weeper.home={x:535,y:318};s.weeper.phase='idle';s.weeper.anger=0;s.weeper.grace=0;s.flashlightOn=false;});
 await page.waitForFunction(()=>window.__nightshift().weeper.noticed&&window.__nightshift().weeper.frame===4);
 assert.equal(await page.evaluate(()=>Number(window.__nightshiftScene.weeperSprite.frame.name)),4);
 assert.equal((await state()).weeper.anger,0);
 await page.screenshot({path:'/tmp/night-shift-patient-quiet-approach.png'});
 await page.evaluate(()=>{window.__nightshiftScene.flashlightOn=true;});
 // Arrange repeatable geometry while using the real input, simulation, lighting and UI.
 await page.evaluate(()=>{const s=window.__nightshiftScene;s.cooldown=999;s.ghostTime=0;s.player.setPosition(458,318);s.weeper.position={x:535,y:318};s.weeper.home={x:535,y:318};s.weeper.phase='idle';s.weeper.grace=0;s.weeper.anger=0;s.angle=0;});
 await page.waitForTimeout(250);await page.screenshot({path:'/tmp/night-shift-crying-patient-idle.png'});
 await page.waitForFunction(()=>window.__nightshift().weeper.phase==='warning');await page.evaluate(()=>window.__nightshiftScene.setPaused(true));await page.screenshot({path:'/tmp/night-shift-crying-patient-warning.png'});const before=await state();await page.evaluate(()=>window.__nightshiftScene.setPaused(false));await page.keyboard.press('f');await page.waitForFunction(()=>window.__nightshift().weeper.phase==='stunned');const saved=await state();assert.equal(saved.health,100);assert.equal(saved.flashes,before.flashes-1);assert.ok(saved.weeper.clock>5.5);await page.screenshot({path:'/tmp/night-shift-crying-patient-flash.png'});
 await page.locator('#pause').click();const frozen=(await state()).weeper.clock;await page.waitForTimeout(300);assert.equal((await state()).weeper.clock,frozen);await page.locator('#resume').click();
 // Viewer flash takes the same path; it also works after the dash has begun.
 await page.evaluate(()=>{const s=window.__nightshiftScene;s.weeper.position={x:540,y:318};s.weeper.phase='dash';s.weeper.angle=Math.PI;s.weeper.clock=.9;});
 const response=await page.request.post(new URL('/api/webhook',page.url()).href,{data:{id:'patient-flash-'+Date.now(),command:'repel',viewer:'test'}});assert.equal(response.status(),200);await page.waitForFunction(()=>window.__nightshift().weeper.phase==='stunned');assert.equal((await state()).health,100);
 await page.evaluate(()=>{const s=window.__nightshiftScene;s.state.battery=0;});const p0=(await state()).player;await page.keyboard.down('Shift');await page.keyboard.press('d',{delay:180});await page.keyboard.up('Shift');const p1=await state();assert.ok(p1.player.x-p0.x>17);assert.ok(p1.stamina<100);await page.screenshot({path:'/tmp/night-shift-empty-battery-readable.png'});
 // An actual locker must extinguish the beam and let a light-shy pursuer leave before eight seconds.
 await page.evaluate(async()=>{const s=window.__nightshiftScene,{patrolPath}=await import('/src/patrol.ts'),{monsterFeetAt}=await import('/src/collision.ts');s.weeper=undefined;s.weeperSprite.setVisible(false);const locker=s.rogue.features.find(f=>f.kind==='locker');s.player.setPosition(locker.x+locker.width/2,locker.y+locker.height/2+28);const route=patrolPath(s.level.monsterSpawns[0],s.player,s.monsterSolids(),s.level.bounds,monsterFeetAt);const start=route.findLast(p=>Math.hypot(p.x-s.player.x,p.y-s.player.y)>125&&Math.hypot(p.x-s.player.x,p.y-s.player.y)<200);if(!start)throw Error('Locker fixture has no approach');s.ghost.setPosition(start.x,start.y);s.ghostTime=20;s.ghostDelay=0;s.stun=0;s.patrolRetreat=false;s.patrolUnseen=0;s.memory=10;s.lastKnown={x:s.player.x,y:s.player.y};s.route=[];s.routeTimer=0;s.state.battery=80;s.flashlightOn=true;s.rules={...s.rules,threat:'light-shy'};});
 await page.keyboard.press('e',{delay:90});await page.waitForFunction(()=>!!window.__nightshift().rogue.hidden);const hiding=await state();assert.equal(hiding.flashlightEffective,false);
 await page.waitForFunction(()=>window.__nightshift().patrolRetreat,{},{timeout:3000});await page.waitForTimeout(2400);const safe=await state();assert.ok(safe.rogue.hidden);assert.equal(safe.battery,hiding.battery);assert.ok(!safe.ghostVisible||Math.hypot(safe.player.x-safe.ghost.x,safe.player.y-safe.ghost.y)>100,JSON.stringify(safe.ghost));await page.screenshot({path:'/tmp/night-shift-locker-light-shy-retreat.png'});await page.keyboard.press('e',{delay:90});await page.waitForFunction(()=>!window.__nightshift().rogue.hidden);assert.equal((await state()).flashlightEffective,true);
 // A full-health stationary player dies in one normal pursuit, even with one second on its budget.
 await page.evaluate(()=>{const s=window.__nightshiftScene;s.weeper=undefined;s.weeperSprite.setVisible(false);s.player.setPosition(458,318);s.ghost.setPosition(480,318);s.ghostTime=1;s.ghostDelay=0;s.patrolRetreat=false;s.patrolUnseen=0;s.route=[];s.routeTimer=0;s.hit=0;s.stun=0;s.protection=0;s.state.health=100;s.state.battery=100;s.cooldown=999;});
 await page.waitForFunction(()=>window.__nightshift().health===0,{},{timeout:14000});assert.equal(await page.locator('#result-screen').getAttribute('data-outcome'),'lost');await page.screenshot({path:'/tmp/night-shift-patrol-idle-death.png'});assert.deepEqual(errors,[]);console.log('Encounter browser checks passed: generated patient, tell, local/viewer flash, pause, empty-battery sprint, light-shy locker retreat and lethal sustained pursuit.');
}finally{await browser.close();}
