import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {goTo,snapshot} from './navigation.mjs';import {feetAt,overlaps} from '../src/collision.ts';
if(process.argv.includes('--rogue-only')){await import('./rogue.browser.mjs');process.exit(0);}
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome-stable',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const first=Number(process.argv[2]||1),rounds=Number(process.argv[3]||3);const use=async()=>{await page.keyboard.press('e',{delay:90});await page.waitForTimeout(160);};
async function approach(v){await goTo(page,v.x,v.y,36);}
try{
 if(first>1)await page.addInitScript(n=>{if(!localStorage.getItem('night-shift-campaign-v1'))localStorage.setItem('night-shift-campaign-v1',JSON.stringify({unlocked:n}));},first);
 await page.addInitScript(()=>localStorage.setItem('night-shift-tutorial-v1',JSON.stringify(['move','key','box','flash','decoy','heal','door','exit'])));await page.goto(process.env.BASE_URL||'http://localhost:5174');await page.locator('#start:enabled').waitFor();assert.equal(await page.locator(`[data-night="${first+1}"]`).isDisabled(),true);await page.screenshot({path:`/tmp/night-shift-stage-select-${first}.png`});await page.locator(`[data-night="${first}"]`).click();await page.locator('#start').click();await page.waitForFunction(n=>window.__nightshift?.().night===n,first);await page.waitForFunction(()=>document.querySelector('#music-status').textContent==='配乐已就绪');
 await page.locator('#console-toggle').click();
 if(first===1){
  const response=await page.request.post(`${new URL(page.url()).origin}/api/webhook`,{data:{id:`endless-${Date.now()}`,command:'reveal',viewer:'侦察测试'}});assert.equal(response.status(),200);await page.waitForTimeout(200);assert.ok((await snapshot(page)).reveal>10);
  await page.locator('[data-command="supply"]').click();assert.equal((await snapshot(page)).flashes,4);await page.locator('[data-command="blackout"]').click();assert.ok((await snapshot(page)).blackout>3);await page.screenshot({path:'/tmp/night-shift-readable-blackout.png'});
  await page.locator('[data-command="ghost"]').click();assert.ok((await snapshot(page)).ghostDelay>2);await page.waitForFunction(()=>{const s=window.__nightshift();return s.ghostDelay===0&&Math.hypot(s.player.x-s.ghost.x,s.player.y-s.ghost.y)<165;},{},{timeout:18000});await page.keyboard.press('f',{delay:100});await page.waitForTimeout(150);assert.ok((await snapshot(page)).stun>3);assert.equal((await snapshot(page)).flashes,3);assert.equal((await snapshot(page)).health,100);
  await page.locator('[data-command="drain"]').click();const beforeDrain=await snapshot(page);assert.ok(beforeDrain.interference.drain>7);await page.waitForTimeout(400);const afterDrain=await page.locator('#battery').textContent();assert.ok(Number(afterDrain)<100);await page.locator('[data-command="alarm"]').click();await page.locator('[data-command="repel"]').click();assert.ok((await snapshot(page)).stun>3);await page.keyboard.press('Escape');await page.locator('#pause').click();const timer=(await snapshot(page)).elapsed;const effects=(await snapshot(page)).interference;await page.waitForTimeout(600);assert.equal((await snapshot(page)).elapsed,timer);assert.deepEqual((await snapshot(page)).interference,effects);await page.locator('#pause').click();
 }
 if(await page.locator('.workspace').evaluate(e=>e.classList.contains('console-closed')))await page.locator('#console-toggle').click();
 page.defend=true;
 for(let offset=0;offset<rounds;offset++){
  const round=first+offset;await page.waitForFunction(n=>window.__nightshift?.().night===n,round);const level=(await snapshot(page)).level;
  await goTo(page,level.doorUse.x,level.doorUse.y);await use();assert.equal((await snapshot(page)).door,false);
  await goTo(page,level.key.x,level.key.y,28);assert.match((await snapshot(page)).interaction.text,/铜钥匙/);await page.screenshot({path:`/tmp/night-shift-world-prompt-${round}.png`});await use();assert.equal((await snapshot(page)).key,true);
  await approach(level.boxes[0]);await use();assert.equal((await snapshot(page)).opened[0],true);assert.match(level.source,/\.ldtk$/);await goTo(page,474,314);await page.waitForFunction(id=>window.__nightshift().events.includes(id),level.events[0].id);assert.deepEqual((await snapshot(page)).eventPending,[]);if(level.theme===0)assert.equal((await snapshot(page)).crtStrength,.36);else assert.equal((await snapshot(page)).environment.LampCenter,.56);
  await approach(level.boxes[1]);await use();assert.equal((await snapshot(page)).opened[1],true);assert.equal((await snapshot(page)).lockKeys.brass,false);assert.equal((await snapshot(page)).lockKeys.seal,true);assert.equal(await page.locator('#puzzle-dialog').isVisible(),false);
  await goTo(page,level.doorUse.x,level.doorUse.y);await use();assert.equal((await snapshot(page)).door,true);assert.equal((await snapshot(page)).lockKeys.ward,false);
  await goTo(page,801,234);await use();assert.equal((await snapshot(page)).door,false);await use();assert.equal((await snapshot(page)).door,true);
  await approach(level.boxes[2]);await use();assert.equal((await snapshot(page)).opened[2],true);assert.ok((await snapshot(page)).exitStartup>0);assert.ok((await snapshot(page)).blackout>5);assert.ok(level.exit.x<level.spawn.x);await page.waitForTimeout(150);assert.equal(await page.locator('#power-countdown').isVisible(),true);await page.screenshot({path:'/tmp/night-shift-power-countdown.png'});assert.deepEqual((await snapshot(page)).lockKeys,{brass:false,ward:false,seal:false});
  await page.screenshot({path:`/tmp/night-shift-map-${round}.png`});await page.locator('[data-command="sanctuary"]').click();await goTo(page,level.exit.x,level.exit.y);await page.waitForFunction(()=>window.__nightshift().exitStartup===0);await use();assert.equal(await page.locator('#result-title').textContent(),'你逃出了这一层。');assert.match(await page.locator('#run-result').textContent(),new RegExp(`第 ${round} 关`));assert.equal(await page.locator('[data-upgrade]').count(),0);assert.equal(await page.locator('#next-night').isDisabled(),false);await page.locator('#next-night').click();await page.waitForFunction(n=>window.__nightshift?.().night===n,round+1);assert.equal((await snapshot(page)).key,false);assert.equal((await snapshot(page)).flashes,1+((await snapshot(page)).rules.event==='supply'?1:0));assert.equal((await snapshot(page)).health,100);assert.deepEqual((await snapshot(page)).interference,{drain:0,alarm:0});assert.deepEqual((await snapshot(page)).eventPending,[]);
 }
 await page.reload();await page.locator('#start:enabled').waitFor();assert.equal(await page.locator(`[data-night="${first+rounds}"]`).isEnabled(),true);assert.equal(await page.locator(`[data-night="${first+rounds+1}"]`).isDisabled(),true);await page.locator('[data-night="1"]').click();assert.match(await page.locator('#start').textContent(),/第 1 关/);
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);console.log(`Endless checks passed: ${rounds} maps starting ${first}, key, locked door, all boxes, escape, next-round reset; ${first===1?'viewer events, readable blackout, warning, F stun, pause; ':''}mobile width, no runtime errors.`);
}catch(e){await page.screenshot({path:'/tmp/endless-failure.png',fullPage:true});throw e;}finally{await browser.close();}

await import('./rogue.browser.mjs');
