import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {EventRuntime,parseEvents} from '../src/runtime/event-runtime.ts';
const data=JSON.parse(readFileSync(new URL('../game/events/ward-return.json',import.meta.url))),yes={flags:{first_box:true},zones:{return_corridor:true}};
test('requires item and zone; waits use simulation time; each event fires once',()=>{const output=[],r=new EventRuntime(parseEvents(data),a=>output.push(a));r.tick(1,{...yes,flags:{}});r.tick(1,{...yes,zones:{}});assert.equal(output.length,0);r.tick(.1,yes);assert.equal(output.length,2);r.tick(0,yes);assert.equal(output.length,2);r.tick(.8,yes);assert.equal(output.filter(a=>a.type==='sound').length,0);r.tick(3,yes);assert.equal(output.at(-1).strength,.36);const n=output.length;r.tick(100,yes);assert.equal(output.length,n);});
test('reset cancels pending effects and permits a fresh run',()=>{const output=[],r=new EventRuntime(parseEvents(data),a=>output.push(a));r.tick(.1,yes);r.reset();const n=output.length;r.tick(10,{flags:{},zones:{}});assert.equal(output.length,n);r.tick(.1,yes);assert.equal(output.length,n+2);});
test('invalid delays, unsupported actions and duplicate IDs are rejected',()=>{assert.throws(()=>parseEvents([...data,...data]));for(const action of [{type:'eval',code:'anything'},{type:'wait',seconds:-1},{type:'wait',seconds:Infinity},{type:'light',target:'missing',strength:1}])assert.throws(()=>parseEvents([{...data[0],sequence:[action]}]));});

test('tracks triggered versus completed, and resets run-local lighting',async()=>{
 const {EnvironmentState}=await import('../src/runtime/environment-state.ts');const environment=new EnvironmentState();
 const definitions=parseEvents([{id:'lights',once:true,trigger:{flag:'first_box',zone:'return_corridor'},sequence:[{type:'light',target:'LampCenter',strength:.1},{type:'wait',seconds:2},{type:'light',target:'LampCenter',strength:.56}]}],['LampCenter']);
 const r=new EventRuntime(definitions,a=>{if(a.type==='light')environment.setLight(a.target,a.strength);});r.tick(.1,yes);assert.deepEqual(r.triggered,['lights']);assert.deepEqual(r.completed,[]);assert.equal(environment.strength('LampCenter',.56),.1);r.tick(0,yes);assert.deepEqual(r.pending,['lights']);r.tick(2,yes);assert.deepEqual(r.completed,['lights']);assert.deepEqual(r.pending,[]);r.reset();environment.reset();assert.equal(environment.strength('LampCenter',.7),.7);assert.deepEqual(r.triggered,[]);
});
test('negative gifts have bounded loss, cannot stack, pause and reset cleanly',async()=>{
 const {Interference}=await import('../src/runtime/interference.ts');const d=new Interference();assert.equal(d.start('drain'),true);assert.equal(d.start('drain'),false);assert.equal(d.tick(0),0);assert.equal(d.drain,8);assert.equal(d.tick(3),6);assert.equal(d.start('drain'),false);assert.equal(d.tick(10),10);assert.equal(d.drain,0);d.start('alarm');d.tick(2);assert.equal(d.alarm,4);d.reset();assert.equal(d.alarm,0);assert.equal(d.drain,0);
});

test('a trailing wait must elapse before an event is completed',()=>{const r=new EventRuntime(parseEvents([{id:'tail',trigger:{flag:'first_box',zone:'return_corridor'},once:true,sequence:[{type:'wait',seconds:2}]}]),()=>{});r.tick(.1,yes);assert.deepEqual(r.completed,[]);r.tick(1,yes);assert.deepEqual(r.pending,['tail']);r.tick(1,yes);assert.deepEqual(r.completed,['tail']);});
