import {goTo,snapshot} from './navigation.mjs';
import {chromium} from '@playwright/test';import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome-stable',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
try{const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('night-shift-tutorial-v1',JSON.stringify(['move','key','box','flash','decoy','heal','door','exit'])));await page.goto(process.env.BASE_URL||'http://localhost:5174');await page.locator('#start:enabled').waitFor();await page.waitForFunction(()=>document.querySelector('#game').dataset.pixelScale);await page.evaluate(()=>document.fonts.ready);assert.equal(await page.evaluate(()=>document.fonts.check('12px NightPixel')),true);await page.screenshot({path:'/tmp/night-shift-ui-title.png'});const size=await page.locator('#game canvas').evaluate(c=>({w:c.width,h:c.height,display:c.getBoundingClientRect().width}));assert.equal(size.w,640);assert.equal(size.h,384);assert.ok(Math.abs(size.display/size.w-2.25)<.01);assert.deepEqual(await page.locator('#game').boundingBox(),{x:0,y:0,width:1440,height:1100});
const metrics=await page.evaluate(async()=>{const {LightRenderer,rayDistance,beamFalloff}=await import('/src/light-renderer.ts');const r=new LightRenderer(),c=document.createElement('canvas');c.width=480;c.height=288;const ctx=c.getContext('2d'),p={x:800,y:450},lamp={x:100,y:200,radius:240,strength:1,color:'#fff'};const alpha=()=>ctx.getImageData(100,100,1,1).data[3];r.render(ctx,[lamp],[],[],p,false);const clear=alpha();r.render(ctx,[lamp],[{x:150,y:100,width:10,height:200}],[],p,false);const blocked=alpha();r.render(ctx,[lamp],[],[{x:150,y:180,width:20,height:40}],p,false);const shadow=alpha();r.render(ctx,[lamp,{...lamp,x:260}],[],[{x:150,y:180,width:20,height:40}],p,false);const filled=alpha();return {clear,blocked,shadow,filled,parallel:rayDistance({x:0,y:0},0,1,{x:10,y:10,width:10,height:10},100),hit:rayDistance({x:0,y:15},1,0,{x:10,y:10,width:10,height:10},100),edge:beamFalloff(.62),middle:beamFalloff(.44),core:beamFalloff(0)};});
assert.ok(metrics.blocked>metrics.clear+40,JSON.stringify(metrics));assert.ok(metrics.shadow>metrics.clear+15);assert.ok(metrics.filled<metrics.shadow);assert.equal(metrics.parallel,100);assert.equal(metrics.hit,10);assert.equal(metrics.edge,0);assert.ok(metrics.middle>0&&metrics.middle<1);assert.equal(metrics.core,1);
await page.locator('#start').click();
await page.waitForFunction(()=>document.querySelector('#music-status')?.textContent==='配乐已就绪');
const decodedMusic=await page.evaluate(async()=>{const tracks=await (await fetch('/game/music.json')).json();const ctx=new AudioContext();try{return await Promise.all(tracks.map(async track=>{const bytes=await (await fetch(track.file)).arrayBuffer();const buffer=await ctx.decodeAudioData(bytes);return {id:track.id,duration:buffer.duration};}));}finally{await ctx.close();}});
assert.equal(decodedMusic.length,9);assert.ok(Math.abs(decodedMusic.find(t=>t.id==='power').duration-8)<.15);console.log('Music ready: nine tracks decoded, power climax eight seconds');
await page.waitForTimeout(400);await page.keyboard.down('Shift');await page.keyboard.down('d');await page.waitForTimeout(240);assert.equal((await snapshot(page)).sprintHeld,true);await page.keyboard.up('Shift');const walkStart=await snapshot(page);await page.waitForTimeout(240);const walkEnd=await snapshot(page);await page.keyboard.up('d');assert.equal(walkEnd.sprintHeld,false);const speed=(walkEnd.player.x-walkStart.player.x)/(walkEnd.elapsed-walkStart.elapsed);assert.ok(speed>75&&speed<90,`released Shift speed ${speed}`);await page.keyboard.down('Shift');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));assert.equal((await snapshot(page)).sprintHeld,false);await page.keyboard.up('Shift');for(const [key,name] of [['a','left'],['s','front'],['w','back'],['d','right']]){await page.keyboard.press(key,{delay:100});await page.screenshot({path:`/tmp/night-shift-character-${name}.png`});}const level=(await snapshot(page)).level;await goTo(page,level.key.x+24,level.key.y);await page.screenshot({path:'/tmp/night-shift-key-detail.png'});await page.keyboard.press('d',{delay:150});await page.screenshot({path:'/tmp/night-shift-lighting-normal.png'});const beforePanel=await page.locator('#game canvas').boundingBox();await page.locator('#console-toggle').click();assert.deepEqual(await page.locator('#game canvas').boundingBox(),beforePanel);await page.locator('[data-command="blackout"]').click();await page.waitForTimeout(300);await page.screenshot({path:'/tmp/night-shift-lighting-blackout.png'});assert.ok(await page.evaluate(()=>window.__nightshift().blackout>0));await page.setViewportSize({width:390,height:844});await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'/tmp/night-shift-pixel-mobile.png'});assert.deepEqual(errors,[]);await page.locator('#pause').click();assert.equal(await page.locator('#pause-menu').isVisible(),true);const elapsed=(await snapshot(page)).elapsed;await page.waitForTimeout(200);assert.equal((await snapshot(page)).elapsed,elapsed);await page.locator('#resume').click();assert.equal(await page.locator('#pause-menu').isVisible(),false);await page.setViewportSize({width:1440,height:900});await page.waitForTimeout(150);if(await page.locator('.workspace').evaluate(e=>e.classList.contains('console-closed')))await page.locator('#console-toggle').click();await page.locator('[data-command="ghost"]').click();await page.waitForFunction(()=>window.__nightshift().health<100,{},{timeout:20000});const hurt=await snapshot(page);await page.locator('[data-item="Q"]').click();await page.waitForFunction(()=>window.__nightshift().feedback.heal>0);const healed=await snapshot(page);assert.equal(healed.feedback.healAmount,healed.health-hurt.health);assert.ok(healed.health>hurt.health);await page.screenshot({path:'/tmp/night-shift-bandage-feedback.png'});console.log('Light checks passed',metrics);
}finally{await browser.close();}

await import('./immersive.browser.mjs');
