import test from 'node:test';import assert from 'node:assert/strict';
import {RogueRun,PressureDirector,cacheOutcome,waterPhase} from '../src/runtime/rogue-run.ts';
import {makeLevel} from '../src/levels.ts';import {center,featureSafetyBox} from '../src/runtime/rogue-content.ts';import {validatePlayableLevel} from '../src/runtime/level-validation.ts';
const feature=(kind,extra={})=>({id:kind,kind,x:100,y:100,width:24,height:20,roll:.7,reward:'flash',...extra});
test('supply cabinet gives exactly one item with one interaction and no surprise alarm',()=>{const r=new RogueRun([feature('cache')]),p={x:112,y:110};assert.match(r.hint(p),/领取/);const outcome=r.interact(p,false);assert.equal(outcome.filter(e=>e.type==='loot').length,1);assert.equal(outcome.some(e=>e.type==='alarm'),false);assert.equal(r.interact(p,false).length,0);assert.match(r.hint(p),/搜空/);assert.equal(r.stats.cachesOpened,1);});
test('hiding is denied in sight, expires on game time, and motion exits',()=>{const f=feature('locker'),r=new RogueRun([f]);r.interact(center(f),true);assert.equal(r.hidden,'');r.interact(center(f),false);r.tick(0,center(f),false,false,false,false);assert.equal(r.hidden,'locker');r.tick(8,center(f),false,false,false,false);assert.equal(r.hidden,'');r.interact(center(f),false);r.tick(.1,center(f),true,false,false,false);assert.equal(r.hidden,'');});
test('hazards warn, cycle off, and blocker has warning and recovery windows',()=>{assert.equal(waterPhase(1),'warning');assert.equal(waterPhase(3),'live');assert.equal(waterPhase(8),'safe');const r=new RogueRun([feature('blocker')]),p={x:112,y:110};r.tick(.1,p,false,false,false,true);assert.equal(r.blockerPhase,'warning');assert.equal(r.tick(1,p,false,false,false,true).some(e=>e.type==='damage'),false);r.tick(1,p,false,false,false,true);assert.equal(r.blockerPhase,'active');r.tick(3,p,false,false,false,true);assert.equal(r.blockerPhase,'idle');r.tick(1,p,false,false,false,true);assert.equal(r.blockerPhase,'idle');});
test('pressure budget bounds gift bursts and protects recovery',()=>{const d=new PressureDirector();assert.ok(d.admit());assert.ok(d.admit());assert.equal(d.admit(),false);d.tick(10,0,0);assert.ok(d.admit());d.hurt();d.tick(0,30,3);assert.equal(d.phase,'喘息');assert.equal(d.admit(),false);d.tick(10,0,3);assert.equal(d.phase,'预警');});
test('optional danger and shortcuts never become requirements in generated maps',()=>{for(const round of [2,3,4])for(let seed=0;seed<20;seed++){const l=makeLevel(round,seed);assert.ok(l.features.filter(f=>f.kind==='cache').length>=1);assert.deepEqual(l.features.map(f=>f.kind),['cache','locker']);const avoid={...l,props:[...l.props,...l.features.map(f=>({...featureSafetyBox(f),kind:'crate'}))]};assert.equal(validatePlayableLevel(avoid).valid,true,`${round}/${seed}`);}});

test('a full inventory leaves the supply in its cabinet for a later visit',()=>{const f=feature('cache'),r=new RogueRun([f]),p=center(f);const result=r.interact(p,false,{flash:3,decoy:1,bandage:1});assert.equal(result.find(e=>e.type==='loot').full,true);assert.equal(r.opened.size,0);assert.equal(r.stats.cachesOpened,0);const claimed=r.interact(p,false,{flash:2,decoy:1,bandage:1});assert.equal(claimed.find(e=>e.type==='loot').full,undefined);assert.equal(r.opened.size,1);});
