import {feetAt,overlaps} from '../src/collision.ts';
import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {goTo,snapshot} from './navigation.mjs';
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome-stable',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
try{
 const page=await browser.newPage({locale:'zh-CN',viewport:{width:1440,height:1000}});page.defend=true;const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{localStorage.setItem('night-shift-campaign-v1',JSON.stringify({unlocked:2}));localStorage.setItem('night-shift-tutorial-v1',JSON.stringify(['move','key','box','flash','decoy','heal','door','exit']));});
 await page.goto(process.env.BASE_URL||'http://localhost:5174');await page.locator('#start:enabled').waitFor();await page.locator('#start').click();await page.waitForFunction(()=>window.__nightshift?.().night===2);await page.locator('#console-toggle').click();
 const initial=await snapshot(page);assert.equal(initial.decoys,1);assert.equal(initial.bandages,1);assert.equal(initial.flashes,1+(initial.rules.event==='supply'?1:0));assert.deepEqual(initial.rogue.features.map(f=>f.kind),['cache','locker']);
 const feature=kind=>initial.rogue.features.find(f=>f.kind===kind),at=f=>({x:f.x+f.width/2,y:f.y+f.height/2+28});
 const cache=feature('cache'),cp=at(cache);await goTo(page,cp.x,cp.y);assert.match((await snapshot(page)).interaction.text,/药柜/);await page.screenshot({path:'/tmp/night-shift-rogue-prompt.png'});await page.keyboard.press('e',{delay:90});await page.waitForTimeout(150);assert.ok((await snapshot(page)).rogue.opened.includes(cache.id));assert.equal((await snapshot(page)).rogue.stats.cachesOpened,1);const gained=await snapshot(page),field={flash:'flashes',decoy:'decoys',bandage:'bandages'}[cache.reward],binding={flash:'F',decoy:'R',bandage:'Q'}[cache.reward];assert.equal(gained[field],initial[field]+1);assert.match(gained.feedback.receipt.text,/×1/);assert.match(gained.feedback.receipt.text,/当前持有/);assert.match(await page.locator('#receipt-message').textContent(),/获得/);await page.locator('[data-command="reveal"]').click();assert.match(await page.locator('#game-message').textContent(),/观众侦察/);assert.match(await page.locator('#receipt-message').textContent(),/获得/);assert.ok(gained.feedback.received[binding]>0);await page.keyboard.press('e',{delay:90});await page.waitForTimeout(150);assert.equal((await snapshot(page)).rogue.stats.cachesOpened,1);await page.screenshot({path:'/tmp/night-shift-rogue-cache.png'});
 const locker=feature('locker'),lp=at(locker);await goTo(page,lp.x,lp.y);assert.match((await snapshot(page)).interaction.text,/藏身柜/);await page.waitForFunction(()=>!window.__nightshift().ghostVisible);await page.keyboard.press('e',{delay:90});await page.waitForTimeout(150);assert.equal((await snapshot(page)).rogue.hidden,locker.id);await page.screenshot({path:'/tmp/night-shift-rogue-locker.png'});await page.keyboard.press('e',{delay:90});await page.waitForTimeout(150);assert.equal((await snapshot(page)).rogue.hidden,'');
 await page.keyboard.press('Escape');await page.locator('#pause').click();const time=(await snapshot(page)).rogue.time;await page.waitForTimeout(600);assert.equal((await snapshot(page)).rogue.time,time);await page.locator('#resume').click();
 assert.deepEqual(errors,[]);console.log('Rogue browser checks passed: reduced loadout, one-shot supply cabinet, hiding locker, paused simulation.');
}catch(e){throw e;}finally{await browser.close();}
