import {summarize} from './telemetry.mjs';
export const pairKey=m=>[m.scenario,m.night,m.seed,m.policy,m.split].join('/');
function searchRows(report){
 return ['','## Optional search exposure','Search policies know furniture locations but not rewards. Bandages and offensive loot are counted independently from spending.','| Night / seed / policy | Search policy | Cabinets searched / placed | Empty tasks searched / placed | Loot gained F / R / Q |','|---|---|---:|---:|---|',...report.runs.map(r=>{const total=Object.values(r.trace.groups).reduce((a,g)=>{a.cabinets+=g.searches?.cabinets??0;a.empty+=g.searches?.empty??0;for(const k of ['F','R','Q'])a.loot[k]+=g.searches?.loot[k]??0;return a;},{cabinets:0,empty:0,loot:{F:0,R:0,Q:0}});return `| ${r.meta.night}/${r.meta.seed}/${r.meta.policy} | ${r.meta.searches??'off'} | ${total.cabinets} / ${r.trace.content?.cabinets??'—'} | ${total.empty} / ${r.trace.content?.empty??'—'} | ${total.loot.F} / ${total.loot.R} / ${total.loot.Q} |`;})];
}
function alarmRows(report){
 const f=n=>n==null?'—':n.toFixed(2),ratio=(n,d)=>d?f(n/d):'—';
 return ['','## Daily and exit countdown','Damage includes hits on healing frames. Pressure excludes nearby suppressed enemies; nearby control is recorded separately. Countdown ends when exit power is ready, even if the player has not escaped.','| Night / seed / policy | Outcome / cause | Daily damage | Countdown seconds | Countdown damage | Countdown pressure | Nearby danger | Nearby control |','|---|---|---:|---:|---:|---:|---:|---:|---:|',...report.runs.map(r=>{const g=r.trace.groups,a=g.finale?.alarm;return `| ${r.meta.night}/${r.meta.seed}/${r.meta.policy} | ${r.trace.result.outcome}${r.trace.result.cause?' / '+r.trace.result.cause:''} | ${f(g.daily?.damage)} | ${f(a?.seconds)} | ${f(a?.damage)} | ${ratio(a?.threatSeconds,a?.seconds)} | ${ratio(a?.nearDangerSeconds,a?.seconds)} | ${ratio(a?.controlledSeconds,a?.seconds)} |`;})];
}
export function compareRuns(baseline,candidate){
 const old=new Map(baseline.map(r=>[pairKey(r.meta),r]));if(old.size!==baseline.length)throw Error('Duplicate baseline pairs');
 const seen=new Set();const pairs=candidate.map(r=>{const key=pairKey(r.meta);if(seen.has(key))throw Error('Duplicate candidate pairs');seen.add(key);const before=old.get(key);if(!before)throw Error('Missing baseline pair '+key);if((before.trace.metricsVersion??1)!==(r.trace.metricsVersion??1)||before.meta.policyVersion!==r.meta.policyVersion||before.meta.seconds!==r.meta.seconds)throw Error('Incompatible policy or duration '+key);return {key,settings:{before:{searches:before.meta.searches??'off',counters:before.meta.counters,movement:before.meta.movement,stamina:before.meta.staminaMode,mixed:before.meta.mixed,weeperAware:before.meta.weeperAware,route:before.meta.route,reserve:before.meta.reserve,items:before.meta.items},after:{searches:r.meta.searches??'off',counters:r.meta.counters,movement:r.meta.movement,stamina:r.meta.staminaMode,mixed:r.meta.mixed,weeperAware:r.meta.weeperAware,route:r.meta.route,reserve:r.meta.reserve,items:r.meta.items}},before:before.trace.result.outcome,after:r.trace.result.outcome,survivalSeconds:{before:before.trace.result.time,after:r.trace.result.time},finaleInventory:{before:before.trace.groups.finale?.inventoryAtStart??null,after:r.trace.groups.finale?.inventoryAtStart??null},stages:Object.fromEntries(Object.entries(r.trace.groups).filter(([stage])=>before.trace.groups[stage]).map(([stage,g])=>[stage,{damage:g.damage-before.trace.groups[stage].damage,threatRatio:g.threatSeconds/Math.max(.001,g.seconds)-before.trace.groups[stage].threatSeconds/Math.max(.001,before.trace.groups[stage].seconds)}]))};});
 if(seen.size!==old.size)throw Error('Baseline and candidate pair sets differ');return pairs;
}
export function markdown(report){
 const f=x=>x===null?'—':Number(x).toFixed(2);return ['# Difficulty benchmark',`Code: ${report.code.commit}; fingerprint: ${report.code.fingerprint}`,`Runs: ${report.runs.length}. Policy v${report.runs[0]?.meta.policyVersion??'?'} follows known objective routes and sees only visible enemies. This is not a novice exploration or human win-rate estimate.`, 'Timeouts and unfinished chases are censored, not successful escapes. Finale fixtures are reported separately. Anomaly flags require inspection; thresholds do not define fair difficulty.', '', '| Scenario/night/policy/stage | Runs | Wins | Timeouts | Damage p50 | Threat ratio p50 | Chase p50 / p90 (s) | Per-enemy re-encounter p50 (s) | Flags |','|---|---:|---:|---:|---:|---:|---:|---:|---:|',...Object.entries(summarize(report.runs)).map(([key,g])=>`| ${key} | ${g.runs} | ${g.wins} | ${g.timeouts} | ${f(g.damageP50)} | ${f(g.threatP50)} | ${f(g.chaseP50)} / ${f(g.chaseP90)} | ${f(g.reencounterP50)} | ${g.anomalies} |`),...alarmRows(report),...searchRows(report),'','## Player-wide recovery','These windows require every enemy to lose its cue and no nearby active danger for at least two seconds. Ongoing windows at run end are censored. They differ from per-enemy escape intervals.','| Night / seed / policy | Route | Reserve | Completed safe windows | Longest completed (s) | Open at end (s) |','|---|---|---:|---:|---:|---:|',...report.runs.map(r=>{const w=r.trace.recovery?.windows??[];return `| ${r.meta.night}/${r.meta.seed}/${r.meta.policy} | ${r.meta.route} | ${r.meta.reserve} | ${w.length} | ${w.length?f(Math.max(...w.map(x=>x.duration))):'—'} | ${f(r.trace.recovery?.open?.duration??null)} |`;}),'',...(report.comparison?['## Paired changes','Negative damage means less damage; positive threat ratio means more time under threat.','```json',JSON.stringify(report.comparison,null,2),'```']:[]),'','Raw JSON contains per-monster exposure, item consumption, censored chases, 30-second diagnostic windows, and paths to full input replays.'].join('\n');
}
