import fs from 'node:fs';import crypto from 'node:crypto';import {locales} from '../../src/i18n/locales.ts';
const en=JSON.parse(fs.readFileSync('game/locales/en.json'));const zh=JSON.parse(fs.readFileSync('game/locales/zh-CN.json'));const status=JSON.parse(fs.readFileSync('game/translation-status.json'));const missing=[];
const overrideSources=JSON.parse(fs.readFileSync('game/localization-override-sources.json'));
for(const file of fs.readdirSync('game/localization-overrides'))if(file.endsWith('.json'))for(const key of Object.keys(JSON.parse(fs.readFileSync('game/localization-overrides/'+file))))if(overrideSources[key]!==en[key])throw new Error('Editorial override source changed: '+file+' '+key+'. Review the override and update localization-override-sources.json.');
for(const l of locales){const file='game/locales/'+(l==='zh-Hans'?'zh-CN':l)+'.json';const data=JSON.parse(fs.readFileSync(file));const overrides='game/localization-overrides/'+l+'.json';if(fs.existsSync(overrides))Object.assign(data,JSON.parse(fs.readFileSync(overrides)));for(const k of Object.keys(en))if(!data[k])missing.push(l+': '+k);fs.writeFileSync(file,JSON.stringify(Object.fromEntries(Object.keys(en).filter(k=>data[k]!==undefined).map(k=>[k,data[k]])),null,2)+'\n');status.locales[l]={...status.locales[l],status:l==='en'||l==='zh-Hans'?'source':'draft',nativeReviewed:false,translatedKeys:Object.keys(en).filter(k=>data[k]).length};}
if(missing.length){console.error(missing.join('\n'));process.exit(1);}
const others=locales.filter(l=>!['en','zh-Hans'].includes(l));fs.writeFileSync('src/i18n/catalogs.ts','// Generated catalog registration shared by both cover variants.\n'+others.map((l,i)=>`import locale${i} from '../../game/locales/${l}.json' with {type:'json'};`).join('\n')+'\nexport const catalogs={'+others.map((l,i)=>JSON.stringify(l)+':locale'+i).join(',')+'};\n');
status.sourceHash=crypto.createHash('sha256').update(JSON.stringify(en)).digest('hex');for(const entry of Object.values(status.locales))entry.sourceHash=status.sourceHash;
status.note='Machine translation drafts with explicit editorial overrides; no native-speaker review claimed.';fs.writeFileSync('game/translation-status.json',JSON.stringify(status,null,2)+'\n');console.log('Finalized',locales.length,'catalogs with',Object.keys(en).length,'keys each.');
