/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false deploy/worker-configuration.d.ts` (hash: fa7edb437f83e5e3dc584cef3a8ea9fd)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./games-worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
