import {storage,flushSave} from './runtime/storage';
import {connectDesktop} from './runtime/desktop-live';
import {ShadeScare} from './ui/shade-scare';
import {toggleFullscreen} from './runtime/fullscreen';
import {GiftPanel} from './ui/gift-panel';
import {giftDefinitions,type GiftEvent} from './runtime/live-gifts';
import {tuning} from './runtime/pacing';
import {assetUrl,corsAssetUrl} from './runtime/asset-url';
import {t as msg,t as translate,setLocale,getLocale,stageName,type MessageKey,localeNames,escapeHtml,htmlMessage,isolate,canvasFont} from './i18n';
import {lessons,isMonsterLesson,type Lesson} from './runtime/tutorial';
import {campaign} from './campaign';
import {makeLevel} from './levels';
import {roundRules,itemRules} from './run-rules';
import {bootGame,type Command} from './endless';
import {Ambience} from './ambience';
import commandCatalog from '../game/commands.json' with {type:'json'};
import {drawSurvey} from './ui/survey';
import {fitDesk} from './ui/fit-desk';
import {mountDeskLamp} from './ui/desk-lamp';
// Both cover variants share the same locale runtime.
const t=translate;
const DEV=(import.meta as unknown as {env:{DEV:boolean}}).env.DEV;
const $=(selector:string)=>document.querySelector<HTMLElement>(selector)!;
const pixelIcon=(path:string)=>`<svg viewBox="0 0 24 24" aria-hidden="true" shape-rendering="crispEdges"><path fill="currentColor" d="${path}"/></svg>`;
const flash=pixelIcon('M10 2h7l-5 8h6L7 23l3-10H5z');
const decoy=pixelIcon('M10 3h4v3h3v10h3v2H4v-2h3V6h3zM10 20h4v2h-4z');
const bandage=pixelIcon('M3 6H8V2H16V6H21V21H3zM10 4V6H14V4zM10 9V12H7V15H10V18H14V15H17V12H14V9z').replace('<path ', '<path fill-rule="evenodd" ');
const key=pixelIcon('M3 4h8v2h2v5h8v3h-2v4h-2v-4h-4v-1h-2v2H3v-2H1V6h2zM4 7v5h6V7z');
const segments=(id:string,count=10)=>`<span id="${id}" class="pixel-segments" role="progressbar" aria-valuemin="0" aria-valuemax="100">${'<i></i>'.repeat(count)}</span>`;
const slots=[['F',msg("ui.flash-device"),flash,'flash-count'],['R',msg("ui.decoy"),decoy,'decoy-count'],['Q',msg("ui.bandage"),bandage,'bandage-count']];
document.querySelector('#app')!.innerHTML=`<svg width="0" height="0" aria-hidden="true" style="position:absolute;pointer-events:none"><defs><filter id="stamp-ink" color-interpolation-filters="sRGB"><feColorMatrix type="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 -4 0 3 0"/></filter></defs></svg><main><div class="workspace console-closed"><section class="left"><div class="game-wrap" id="game-wrap"><div id="game"></div><div class="game-vignette"></div>
<div id="play-hud"><div class="screen-heading"><span id="night-name">${htmlMessage("ui.night-shift-records")}</span><nav>${DEV?`<button id="console-toggle" aria-expanded="false">${htmlMessage("ui.developer-controls")}</button>`:''}<button id="pause" aria-expanded="false" aria-controls="pause-menu">${htmlMessage("ui.menu-esc")}</button></nav></div>
<div class="game-hud"><span>● REC</span><span id="timer">00:00</span></div><div class="location"><b></b></div><div id="game-message" aria-live="polite"></div>
<div class="game-bottom status-panel"><div class="vital-row"><span>${htmlMessage("ui.health")}<b id="health">100</b></span><span id="health-bar" class="solid-health" role="progressbar" aria-label="${htmlMessage("ui.health-041")}" aria-valuemin="0" aria-valuemax="100"><span class="health-loss" aria-hidden="true"></span><span class="health-fill" aria-hidden="true"></span></span><small id="health-caption">${htmlMessage("ui.stable")}</small></div><div class="vital-row"><span>${htmlMessage("ui.stamina")}<b id="stamina">100</b></span>${segments('stamina-bar')}<small id="stamina-caption">${htmlMessage("ui.ready-to-sprint")}</small></div><button id="flashlight-toggle" type="button" aria-label="${htmlMessage("ui.toggle-flashlight-t")}" aria-pressed="true"><svg viewBox="0 0 24 24" aria-hidden="true" shape-rendering="crispEdges"><path fill="currentColor" d="M7 2H17V5H19V10H17V22H7V10H5V5H7ZM9 11V20H15V11ZM8 5V8H16V5Z"/><path class="torch-ray" fill="currentColor" d="M1 1H3V4H1ZM21 1H23V4H21Z"/></svg><span class="flashlight-heading">${htmlMessage("ui.flashlight-battery")}</span><span class="flashlight-charge"><b id="battery">100</b>%</span><span id="flashlight-mode">${htmlMessage("ui.on-seconds")}</span></button><div class="minor-status"><span>${htmlMessage("ui.fuses")}<b id="fuses">0 / 3</b></span></div></div>
<div id="vital-distress" aria-hidden="true"></div><section id="power-countdown" hidden role="timer" aria-label="${htmlMessage("ui.exit-power-countdown")}"><small id="power-label">${htmlMessage("ui.emergency-power-starting")}</small><b id="power-seconds">30</b>${segments('power-progress',8)}<span id="power-hint">${htmlMessage("ui.keep-moving")}</span></section>
<div class="inventory-hud" aria-label="${htmlMessage("ui.inventory")}">${slots.map(([binding,label,icon,id])=>`<button class="item-slot" data-item="${binding}" title="${binding} · ${escapeHtml(label)}" aria-label="${htmlMessage('item.use',{item:label})}"><kbd>${binding}</kbd>${icon}<span>${escapeHtml(label)}</span><b id="${id}">0</b></button>`).join('')}<div class="item-slot key-slot" title="${htmlMessage("ui.special-keys-held")}">${key}<span id="key-label">${htmlMessage("ui.keys")}</span><b id="key-count">0</b></div></div>
<div class="phase-hud"><span id="run-phase">${htmlMessage("ui.search")}</span><span id="objective"></span></div>
</div><div class="start-layer" id="start-layer">
<div class="desk-scene" aria-hidden="true"></div><div class="desk-interference" aria-hidden="true"></div>
<div class="desk-content"><div class="desk-title"><span class="desk-kicker">${htmlMessage("menu.hospital")}</span><h2 class="game-brand"><img crossorigin="anonymous" src="${corsAssetUrl('/assets/yakin-byoutou-title-alpha-v1.webp')}" width="2048" height="768" alt="夜勤病棟" draggable="false"></h2><p>${htmlMessage("menu.subtitle")}</p></div>
<section class="patrol-book" aria-label="${htmlMessage("ui.patrol-records")}"><div class="book-header"><span>${htmlMessage("ui.night-patrol-logbook")}</span><span id="stage-progress"></span></div><nav class="book-tabs"><button id="book-guide"></button><button id="desk-settings"></button><label for="menu-language" id="language-label"></label><select id="menu-language" aria-labelledby="language-label">${Object.entries(localeNames).map(([code,name])=>`<option value="${code}" lang="${code}">${escapeHtml(name)}</option>`).join('')}</select></nav>
<div class="book-body"><div class="archive-index"><div class="index-label">${htmlMessage("ui.number-patrol-area")}</div><div class="night-select" id="stage-list"></div><div class="stage-pages"><button id="stage-prev" aria-label="${htmlMessage("menu.previous")}">←</button><span id="stage-page"></span><button id="stage-next" aria-label="${htmlMessage("menu.next")}">→</button></div></div>
<div class="archive-sheet"><div class="record-heading"><span class="file-code" id="file-code"></span><span class="file-stamp" id="file-stamp"></span></div><h3 id="file-title"></h3><p id="file-date"></p><div class="survey-frame"><canvas id="survey" width="240" height="144" aria-label="${htmlMessage("ui.archived-image-of-selected-area")}"></canvas><span>${htmlMessage("ui.archived-footage-not-live")}</span></div><p id="file-note"></p><p id="stage-detail"></p></div></div>
<div class="book-footer"><button id="start" disabled>${htmlMessage("menu.loading")}</button></div></section>
<div class="desk-footnote"><span>${htmlMessage("menu.warning")}</span><span class="desk-clock">02:17</span></div></div>
<div class="monitor-caption" aria-hidden="true"><i></i>${htmlMessage("ui.cam-unstable-signal")}<span>${htmlMessage("ui.duty-room")}</span></div></div>
<section id="pause-menu" hidden aria-label="${htmlMessage("ui.game-menu")}"><h2>${htmlMessage("settings.title")}</h2><button id="resume">${htmlMessage("ui.return-to-game")}</button><button id="guide">${htmlMessage("settings.guide")}</button><button id="sound">${htmlMessage("settings.soundOn")}</button><label><span id="volume-label">${htmlMessage("settings.volume")}</span> <input id="music-volume" type="range" min="0" max="100" value="42" aria-label="${htmlMessage("ui.music-volume")}"></label><small id="music-track">${htmlMessage("ui.music-night-reception")}</small><small id="music-status">${htmlMessage("audio.waiting")}</small><button id="fullscreen">${htmlMessage("settings.fullscreen")}</button><button id="menu-stages">${htmlMessage("settings.stages")}</button><p id="round-rule"></p></section>
<section id="tutorial-card" hidden role="dialog" aria-modal="true" aria-labelledby="tutorial-title"><small>${htmlMessage("ui.field-guide-paused")}</small><h2 id="tutorial-title"></h2><p id="tutorial-copy"></p><div><button id="tutorial-continue">${htmlMessage("ui.understood-try-it")}</button><button id="tutorial-practice-skip" hidden>${htmlMessage("ui.learn-after-an-injury")}</button><button id="tutorial-skip">${htmlMessage("ui.skip-this-tutorial")}</button></div></section><section id="result-screen" hidden aria-labelledby="result-title"><div class="result-document"><div class="document-head" id="result-kicker">${htmlMessage("ui.night-patrol-records")}</div><h2 id="result-title"></h2><section id="run-result" hidden></section><div class="result-actions"><button id="next-night" hidden>${htmlMessage("ui.next-stage")}</button><button id="result-retry">${htmlMessage("ui.retry-stage")}</button><button id="result-menu">${htmlMessage("settings.stages")}</button></div></div></section>
<div class="threat-screen" id="threat-screen" aria-hidden="true"></div><div class="danger-flash" id="flash" aria-hidden="true"><i></i><i></i><i></i></div></div></section>
${DEV?`<aside class="interaction"><div class="panel-heading"><h2>${htmlMessage("ui.developer-controls")}</h2><small>${htmlMessage("ui.development-builds-only")}</small></div><div class="gift-list">${commandCatalog.map(c=>`<button class="gift-card" data-command="${c.id}"><div class="gift-icon">${c.icon}</div><div class="gift-copy"><h3>${htmlMessage(('command.'+c.id) as MessageKey)} · ${c.kind==='buff'?msg("ui.buff"):msg("ui.debuff")}</h3><p>${htmlMessage(('command.'+c.id+'.description') as MessageKey)}</p></div></button>`).join('')}</div></aside>`:''}</div></main>
<dialog id="guide-dialog"><h2>${htmlMessage("guide.title")}</h2><p>${htmlMessage("ui.wasd-arrows-to-move-shift-to-sprint")}</p><p>${htmlMessage("ui.f-repels-nearby-monsters-r-drops-a")}</p><p>${htmlMessage("ui.t-or-the-battery-icon-toggles-the")}</p><p>${htmlMessage("ui.searching-raises-danger-the-final-fuse-starts")}</p><p>${htmlMessage("ui.from-stage-carry-one-flash-decoy-and")}</p><button id="close-guide">${htmlMessage("guide.close")}</button></dialog><div id="toast" role="status"></div>`;
// A missing optional font must not prevent entering the game.
await document.fonts.load('12px '+canvasFont()).catch(error=>console.warn('Locale font unavailable',error));
fitDesk($('#start-layer'),$('.desk-content'));
const gameOverlay=document.createElement('div');gameOverlay.className='game-overlay-stage';$('#game-wrap').append(gameOverlay);gameOverlay.append($('#tutorial-card'),$('#result-screen'));
const fieldBelt=document.createElement('div');fieldBelt.className='field-belt';fieldBelt.setAttribute('aria-label',msg("ui.quick-items"));$('#play-hud').append(fieldBelt);fieldBelt.append($('.inventory-hud'));
const mission=document.createElement('section');mission.id='mission-hud';mission.setAttribute('aria-label',msg("ui.escape-supplies"));mission.innerHTML=`<small>${htmlMessage("ui.escape-preparations")}</small>`;mission.append($('.minor-status'),$('.key-slot'),$('#flashlight-toggle'));$('#play-hud').append(mission);
$('.status-panel').insertAdjacentHTML('afterbegin',`<small class="monitor-label">${htmlMessage("ui.vital-signs")}<i aria-hidden="true"></i></small>`);
const receipt=document.createElement('section');receipt.id='receipt-message';receipt.hidden=true;receipt.setAttribute('role','status');$('#play-hud').append(receipt);
let environmentMessage='';let receiptMessage='';let receiptItem:string|undefined;
function renderMessage(){
 for(const [selector,text] of [['#game-message',environmentMessage],['#receipt-message',receiptMessage]]){
  const el=$(selector);el.hidden=!text;if(el.dataset.copy===text)continue;el.dataset.copy=text;el.replaceChildren();
  if(selector==='#receipt-message'){const mark=document.createElement('div');mark.className='receipt-mark';mark.innerHTML=receiptItem==='F'?flash:receiptItem==='R'?decoy:receiptItem==='Q'?bandage:pixelIcon('M8 2h8v3h2v14h-2v3H8v-3H6V5h2zM9 6h6v12H9z');mark.setAttribute('aria-hidden','true');el.append(mark);}
  const lines=text.split('\n'),copy=document.createElement('div');copy.className='message-copy';const title=document.createElement('span');title.className='message-title';title.textContent=lines[0];copy.append(title);
  if(lines.length>1){const detail=document.createElement('span');detail.className='message-detail';detail.textContent=lines.slice(1).join(' ');copy.append(detail);}el.append(copy);
 }
}
function resumeNight(){try{const n=JSON.parse(storage.getItem('night-shift-current-run-v1')??'null')?.night;return campaign.canPlay(n)?n:campaign.unlocked;}catch{return campaign.unlocked;}}
const STAGES_PER_PAGE=7;
let previousHealth=100;let lastFeedbackTime=0;let barHealth=100;let teaching:Lesson|null=null;let giftQueue:{command:Command;viewer:string}[]=[];let nextGiftAt=0;let running=false,paused=false,audioOn=true,selectedNight=resumeNight(),stagePage=Math.floor((selectedNight-1)/STAGES_PER_PAGE),toastTimer:ReturnType<typeof setTimeout>;
document.body.dataset.ui='title';
const ambience=new Ambience();
try{const settings=JSON.parse(storage.getItem('night-shift-settings-v1')??'{}');audioOn=settings.audioOn!==false;void ambience.setEnabled(audioOn).catch(console.error);if(typeof settings.volume==='number'){ambience.setVolume(settings.volume);(document.querySelector('#music-volume') as HTMLInputElement).value=String(settings.volume*100);}}catch{}
function saveSettings(){storage.setItem('night-shift-settings-v1',JSON.stringify({audioOn,volume:Number((document.querySelector('#music-volume') as HTMLInputElement).value)/100}));}
mountDeskLamp($('.desk-scene'),(delay,depth)=>ambience.coverApparition(delay,depth));
let currentTrack='menu',currentChase=false;
const trackNames:Record<string,string>={menu:msg("ui.night-reception"),ward:msg("music.ward"), 'ward-alt':msg("music.ward-alt"),warehouse:msg("music.warehouse"),'warehouse-alt':msg("music.warehouse-alt"),plant:msg("music.plant"),'plant-alt':msg("music.plant-alt")};
ambience.onTrack=(id,chasing)=>{currentTrack=id;currentChase=chasing;$('#music-track').textContent=t('audio.track',{name:id==='garden-blood-moon'?t('stage.6'):trackNames[id]?t(('music.'+id) as MessageKey):id})+(chasing?t('audio.chase'):'');$('#music-track').dataset.track=id;};
function toast(text:string){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2500);}
const shadeScare=new ShadeScare(document.querySelector<HTMLElement>('#game-wrap')!);
const giftPanel=new GiftPanel(document.querySelector<HTMLElement>('#game-wrap')!);
const game=bootGame({onMonsterDeath(source,kind){shadeScare.show(source,kind);},onShadeDeath(source){shadeScare.show(source);},onGiftFrame(){giftPanel.drawFrame();shadeScare.drawFrame();},onGifts(view,fx){const host=document.querySelector<HTMLElement>('#game-wrap')!;if(host.dataset.runId!==view.runId){shadeScare.clear();host.dataset.runId=view.runId;window.dispatchEvent(new CustomEvent('nightshift:run',{detail:{runId:view.runId}}));}giftPanel.render(view,fx);},onReady(){$('#start').removeAttribute('disabled');},onCue(kind,pan,volume){ambience.cue(kind,pan,volume);},onState(s){
 receiptMessage=s.feedback.receipt?.text??'';receiptItem=s.feedback.receipt?.item;renderMessage();
 const flashlight=$('#flashlight-toggle'),lightMode=s.flashlightBlocked?msg("ui.light-covered-while-hiding"):s.battery<=0?msg("ui.battery-empty"):!s.flashlightOn?msg("ui.t-to-turn-on-off"):s.battery<=20?msg("ui.t-to-toggle-only-seconds", {seconds:s.lightSeconds}):msg("ui.t-to-toggle-seconds-left", {seconds:s.lightSeconds});$('#flashlight-mode').textContent=lightMode;flashlight.setAttribute('aria-pressed',String(s.flashlightOn));flashlight.setAttribute('aria-label',msg("ui.flashlight-press-t-or-click-to-toggle", {battery:Math.ceil(s.battery),mode:lightMode}));flashlight.dataset.empty=String(s.battery<=0);flashlight.dataset.low=String(s.battery>0&&s.battery<=20);flashlight.dataset.blocked=String(s.flashlightBlocked);
 const changed=teaching!==s.tutorial;teaching=s.tutorial;$('#tutorial-card').hidden=!teaching||(teaching==='exit'&&s.exitTour!=='hold');document.body.classList.toggle('teaching',!!teaching);document.querySelectorAll('.tutorial-target').forEach(e=>e.classList.remove('tutorial-target'));if(teaching){const lesson=lessons[teaching];$('#tutorial-skip').hidden=isMonsterLesson(teaching);$('#tutorial-title').textContent=lesson.title;$('#tutorial-copy').textContent=teaching==='exit'?t('tutorial.exitText',{seconds:tuning.exitStartup}):lesson.text;if(teaching==='exit')$('#tutorial-title').textContent=t('tutorial.exitTitle');if(teaching==='health'||teaching==='flashlight'||isMonsterLesson(teaching)){$('#tutorial-title').textContent=t(('tutorial.'+teaching+'Title') as MessageKey);$('#tutorial-copy').textContent=t(('tutorial.'+teaching+'Text') as MessageKey,teaching==='monster-patroller'?{seconds:itemRules.flashDuration}:{});}$('#tutorial-continue').textContent=isMonsterLesson(teaching)?t('tutorial.monsterContinue'):teaching==='exit'?t('tutorial.exitReturn'):teaching==='practice'?msg("ui.simulate-injury-and-practise-bandaging"):msg("ui.understood-try-it");$('#tutorial-practice-skip').hidden=teaching!=='practice';const target=lesson.target;if(target!=='world')document.querySelector(target==='stamina'?'.game-bottom':target==='key'?'.key-slot':target==='health'?'#health-bar':target==='light'?'#flashlight-toggle':`[data-item="${target}"]`)?.classList.add('tutorial-target');if(changed){$('#tutorial-continue').focus({preventScroll:true});ambience.setRunning(false);}}else if(changed){nextGiftAt=s.elapsed+3;ambience.setRunning(running&&!paused);}if(!teaching&&!s.tutorialPracticing&&running&&!paused&&giftQueue.length&&s.elapsed>=nextGiftAt){const gift=giftQueue.shift()!;nextGiftAt=s.elapsed+3;queueMicrotask(()=>receive(gift.command,gift.viewer));}
 document.body.dataset.frozen=String(paused||!!teaching||!running);
 const dt=Math.max(0,s.elapsed-lastFeedbackTime);if(s.elapsed<lastFeedbackTime){barHealth=s.health;previousHealth=s.health;}lastFeedbackTime=s.elapsed;barHealth=s.health>barHealth?Math.min(s.health,barHealth+dt*65):s.health;
 for(const [id,value] of [['stamina-bar',s.stamina],['power-progress',(tuning.exitStartup-s.exitStartup)/tuning.exitStartup*100]] as const){const bar=$('#'+id),cells=bar.children;bar.setAttribute('aria-valuenow',String(Math.round(value)));for(let i=0;i<cells.length;i++){(cells[i] as HTMLElement).dataset.filled=String(i<Math.ceil(value/100*cells.length));}}
 const healthBar=$('#health-bar');healthBar.setAttribute('aria-valuenow',String(Math.ceil(s.health)));
 const healthColumns=Math.ceil(Math.max(0,Math.min(100,barHealth))*60/100),lossColumns=Math.ceil(Math.max(0,Math.min(100,s.feedback.damage>0?Math.max(s.health,previousHealth):s.health))*60/100);
 healthBar.style.setProperty('--health-fill',`${healthColumns/60*100}%`);healthBar.style.setProperty('--health-loss',`${lossColumns/60*100}%`);

 if(s.feedback.damage===0)previousHealth=s.health;
 $('.status-panel').dataset.danger=String(s.health<=30);$('.status-panel').dataset.healing=String(s.feedback.heal>0);$('#health-caption').textContent=s.feedback.heal>0?msg("ui.healing", {health:s.feedback.healAmount}):s.health<=30?msg("ui.danger-blood-loss"):s.health<60?msg("ui.injured"):msg("ui.stable");$('.status-panel').dataset.staminaActive=String(s.stamina<100||s.exhausted||!!s.tutorial);$('#stamina-caption').textContent=s.exhausted?msg("ui.catch-your-breath"):s.stamina<30?msg("ui.low-stamina"):msg("ui.ready-to-sprint");$('#stamina-bar').dataset.low=String(s.stamina<30);$('#vital-distress').style.opacity=String(running&&!paused&&!teaching?Math.max(s.health<=30?.4:0,s.feedback.damage*.9):0);$('#vital-distress').dataset.side=s.feedback.hitSide;
 const power=s.exitStartup>0||s.feedback.exitReady>0;$('#power-countdown').hidden=!power||!!teaching||!running;$('#power-countdown').dataset.urgent=String(s.exitStartup>0&&s.exitStartup<=10);$('#power-countdown').dataset.ready=String(s.exitStartup===0);$('#power-countdown').dataset.beat=String(Math.floor(s.elapsed*5)%2);$('#power-seconds').textContent=s.exitStartup>0?String(Math.ceil(s.exitStartup)).padStart(2,'0'):'OPEN';$('#power-label').textContent=s.exitStartup>0?msg("ui.emergency-power-starting"):msg("ui.exit-powered");$('#power-hint').textContent=s.exitStartup>0?msg("ui.keep-moving-prepare-to-escape"):msg("ui.go-to-exit-press-e-to-escape");
 for(const binding of ['F','R','Q'] as const){const slot=document.querySelector<HTMLElement>(`[data-item="${binding}"]`)!;slot.dataset.used=String(s.feedback.used[binding]>0);slot.dataset.available=String(binding==='Q'?s.health<100&&s.bandages>0:false);}
 $('#health').textContent=String(Math.ceil(s.health));$('#battery').textContent=String(Math.ceil(s.battery));$('#fuses').textContent=`${s.fuses} / 3`;$('#stamina').textContent=String(Math.ceil(s.stamina));$('#stamina').dataset.low=String(s.stamina<30);$('#run-phase').textContent=s.phase;$('#objective').textContent=s.objective;$('#round-rule').textContent=t('hud.ruleVitals',{rule:s.rule,health:Math.ceil(s.health),stamina:Math.ceil(s.stamina)});$('#night-name').textContent=msg('menu.night-title',{night:s.night,area:s.map});$('.location>b').textContent=s.map;
 $('#flash-count').textContent=String(s.flashes);$('#decoy-count').textContent=String(s.decoys);$('#bandage-count').textContent=String(s.bandages);$('#key-count').textContent=String(s.keyCount);$('#key-label').textContent=s.keyNames||msg("ui.keys");for(const [binding,count] of [['F',s.flashes],['R',s.decoys],['Q',s.bandages]] as const)document.querySelector<HTMLButtonElement>(`[data-item="${binding}"]`)!.disabled=count===0;
 for(const binding of ['F','R','Q'] as const)$(`[data-item="${binding}"]`).dataset.received=String(s.feedback.received[binding]>0);
 $('#timer').textContent=`${Math.floor(s.elapsed/60).toString().padStart(2,'0')}:${Math.floor(s.elapsed%60).toString().padStart(2,'0')}`;$('#threat-screen').style.opacity=String(running&&!paused&&!teaching?s.pressure:0);ambience.setScene(running?s.theme:-2,running?s.pressure:0,running?s.exitStartup:0,s.night,running?s.fuses:0,running?s.bloodMoon:0);
},onMessage(text){environmentMessage=text;renderMessage();},onHit(){$('#flash').classList.remove('hit');void $('#flash').offsetWidth;$('#flash').classList.add('hit');},onEnd(result){
 giftQueue=[];running=false;paused=false;selectedNight=result.night;$('#pause-menu').hidden=true;$('#pause').setAttribute('aria-expanded','false');$('#result-screen').hidden=false;$('#result-screen').dataset.outcome=result.won?'won':'lost';$('#game-wrap').classList.add('run-ended');$('#result-kicker').textContent=result.won?msg("ui.survivor-record-floor-cleared"):msg("ui.missing-person-record-no-response");$('#result-title').textContent=result.won?msg("ui.you-escaped-this-floor"):msg("ui.patrol-signal-lost");$('#run-result').hidden=false;$('#run-result').innerHTML=`<h3>${htmlMessage('menu.night-title',{night:result.night,area:result.map})}</h3><div class="result-stats"><span><b>${htmlMessage("result.seconds",{seconds:Math.floor(result.elapsed)})}</b>${htmlMessage("ui.patrol-duration")}</span><span><b>${Math.ceil(result.health)}</b>${htmlMessage("ui.health-remaining")}</span><span><b>${result.fuses} / 3</b>${htmlMessage("ui.fuses-040")}</span></div>${result.night>1?`<p>${htmlMessage("result.extras",{searches:result.rogue.cachesOpened,hides:result.rogue.hides})}</p>`:''}`;$('#next-night').hidden=!result.won;$('#next-night').textContent=msg("ui.enter-stage", {stage:result.night+1});$('#threat-screen').style.opacity='0';$('#flash').classList.remove('hit');ambience.setScene(-2,0,0);ambience.setRunning(true);$(result.won?'#next-night':'#result-retry').focus({preventScroll:true});
}});
function menu(open:boolean){if(teaching)return;(running?gameOverlay:$('#game-wrap')).append($('#pause-menu'));$('#pause-menu').hidden=!open;$('#pause').setAttribute('aria-expanded',String(open));if(running){paused=open;game.setPaused(open);ambience.setRunning(!open);}if(open&&DEV)$('.workspace').classList.add('console-closed');}
function enterAudio(){if(audioOn){ambience.setRunning(true);void ambience.setEnabled(true).catch(()=>toast(msg("ui.use-the-sound-button-in-the-menu")));}}
function start(){shadeScare.clear();giftQueue=[];if(!campaign.canPlay(selectedNight))return;document.body.dataset.ui='playing';applyMenuLanguage();$('#start-layer').classList.add('hidden');$('#result-screen').hidden=true;$('#game-wrap').classList.remove('run-ended');running=true;menu(false);ambience.beginRun(makeLevel(selectedNight).theme,selectedNight);game.startRun(selectedNight);enterAudio();}
$('#flashlight-toggle').onclick=()=>game.toggleFlashlight();let signing=false;$('#start').onclick=()=>{if(signing)return;signing=true;enterAudio();$('.patrol-book').classList.add('signing');$('#file-stamp').textContent=t('menu.signed');setTimeout(()=>{signing=false;$('.patrol-book').classList.remove('signing');start();},420);};$('#result-retry').onclick=start;
$('#pause').onclick=()=>menu($('#pause-menu').hidden);$('#resume').onclick=()=>menu(false);
$('#book-guide').onclick=()=>document.querySelector<HTMLDialogElement>('#guide-dialog')!.showModal();
$('#guide').onclick=()=>document.querySelector<HTMLDialogElement>('#guide-dialog')!.showModal();$('#close-guide').onclick=()=>document.querySelector<HTMLDialogElement>('#guide-dialog')!.close();
$('#sound').onclick=()=>{audioOn=!audioOn;saveSettings();void ambience.setEnabled(audioOn).catch(()=>toast(msg("ui.could-not-enable-audio-please-retry")));};ambience.onStatus=status=>{$('#music-status').dataset.status=status;$('#music-status').textContent=audioStatus(status);audioOn=ambience.enabled;$('#sound').textContent=t(audioOn?'settings.soundOn':'settings.soundOff');};$('#music-volume').oninput=e=>{ambience.setVolume(Number((e.target as HTMLInputElement).value)/100);saveSettings();};$('#desk-settings').onclick=()=>menu(true);$('#start-layer').addEventListener('pointerdown',()=>{if(audioOn)enterAudio();},{once:true});
$('#fullscreen').onclick=()=>{void toggleFullscreen($('#game-wrap')).catch(()=>toast(msg("ui.this-browser-does-not-support-fullscreen")));};
function renderStages(){
 const pages=Math.ceil((campaign.unlocked+1)/STAGES_PER_PAGE);stagePage=Math.max(0,Math.min(stagePage,pages-1));
 $('#stage-progress').textContent=t('menu.archive',{count:String(campaign.unlocked-1).padStart(2,'0')});
 $('#stage-list').innerHTML=Array.from({length:STAGES_PER_PAGE},(_,i)=>{const n=stagePage*STAGES_PER_PAGE+i+1;return `<button data-night="${n}" ${campaign.canPlay(n)?'':'disabled'} class="${n===selectedNight?'selected':''}" aria-pressed="${n===selectedNight}" aria-label="${htmlMessage('menu.night-title',{night:n,area:stageName(makeLevel(n).theme)})}" aria-description="${htmlMessage(n<campaign.unlocked?'menu.filed':campaign.canPlay(n)?'menu.available':'menu.locked')}"><span class="stage-number">${htmlMessage('menu.night',{night:n})}</span><b>${escapeHtml(stageName(makeLevel(n).theme))}</b></button>`;}).join('');
 $('#stage-page').textContent=t('menu.page',{page:String(stagePage+1).padStart(2,'0'),total:String(pages).padStart(2,'0')});
 $('#stage-prev').toggleAttribute('disabled',stagePage===0);$('#stage-next').toggleAttribute('disabled',stagePage>=pages-1);
 const rule=roundRules(selectedNight),level=makeLevel(selectedNight);
 $('#file-code').textContent=t('menu.record',{number:String(selectedNight).padStart(3,'0')});$('#file-title').textContent=t('menu.night-title',{night:selectedNight,area:stageName(level.theme)});
 const shiftDate=new Date(Date.UTC(1998,9,14+selectedNight-1));
 $('#file-date').textContent=t('menu.shift-date',{date:new Intl.DateTimeFormat(getLocale(),{year:'numeric',month:'numeric',day:'numeric',timeZone:'UTC'}).format(shiftDate),weekday:'d'+shiftDate.getUTCDay()});
 $('#file-note').textContent=t(('note.'+level.theme) as MessageKey);
 $('#stage-detail').textContent=t('menu.anomaly',{threat:t(('threat.'+rule.threat) as MessageKey),event:t(('event.'+rule.event) as MessageKey)});
 $('#file-stamp').textContent=t(selectedNight<campaign.unlocked?'menu.complete':'menu.pending');
 $('#file-stamp').dataset.complete=String(selectedNight<campaign.unlocked);
 $('#start').textContent=t('menu.start',{number:selectedNight});
 drawSurvey(document.querySelector<HTMLCanvasElement>('#survey')!,level);
 document.querySelectorAll<HTMLButtonElement>('[data-night]').forEach(b=>b.onclick=()=>{selectedNight=Number(b.dataset.night);renderStages();document.querySelector<HTMLButtonElement>(`[data-night="${selectedNight}"]`)?.focus({preventScroll:true});ambience.setScene(-2,0,0);});
}
function title(){storage.removeItem('night-shift-current-run-v1');game.clearGifts();ambience.setScene(-2,0,0);giftQueue=[];running=false;paused=false;game.setPaused(true);menu(false);document.body.dataset.ui='title';$('#result-screen').hidden=true;$('#game-wrap').classList.remove('run-ended');$('#start-layer').classList.remove('hidden');selectedNight=resumeNight();stagePage=Math.floor((selectedNight-1)/STAGES_PER_PAGE);applyMenuLanguage();ambience.setRunning(true);}
$('#menu-stages').onclick=title;$('#result-menu').onclick=title;$('#stage-prev').onclick=()=>{stagePage--;turnPage();};$('#stage-next').onclick=()=>{stagePage++;turnPage();};applyMenuLanguage();
$('#next-night').onclick=()=>{if(!game.continueRun())return;ambience.beginRun(makeLevel(selectedNight+1).theme,selectedNight+1);running=true;paused=false;document.body.dataset.ui='playing';$('#result-screen').hidden=true;$('#game-wrap').classList.remove('run-ended');ambience.setRunning(true);};
document.querySelectorAll<HTMLButtonElement>('[data-item]').forEach(b=>b.onclick=()=>{if(running&&!paused)game.useItem(b.dataset.item as 'F'|'R'|'Q');b.blur();});
function receive(command:Command,viewer:string){if(teaching){if(giftQueue.length<8)giftQueue.push({command,viewer});return;}if(!running||paused)return;game.command(command);const entry=commandCatalog.find(c=>c.id===command);if(entry)toast(t('viewer.command',{viewer:isolate(viewer),command:t(('command.'+entry.id) as MessageKey)}));}
if(DEV){$('#console-toggle').onclick=()=>{const closed=$('.workspace').classList.toggle('console-closed');$('#console-toggle').setAttribute('aria-expanded',String(!closed));};document.querySelectorAll<HTMLButtonElement>('[data-command]').forEach(b=>b.onclick=()=>{receive(b.dataset.command as Command,msg("ui.test-viewer"));b.disabled=true;setTimeout(()=>b.disabled=false,800);});}
// The Vite webhook is a local test adapter; production requires an explicit event endpoint.
const eventsUrl=(import.meta as unknown as {env:{VITE_EVENTS_URL?:string}}).env.VITE_EVENTS_URL;
let stream:EventSource|undefined;
if(DEV||eventsUrl){stream=new EventSource(eventsUrl||'/api/events');stream.onmessage=e=>{try{const data=JSON.parse(e.data);if(data.giftId&&giftDefinitions[data.giftId as keyof typeof giftDefinitions]){game.gift(data as GiftEvent);return;}if(commandCatalog.some(c=>c.id===data.command)&&typeof data.viewer==='string')receive(data.command,data.viewer);}catch{}};}
window.addEventListener('keydown',e=>{if(teaching){if(e.key==='Escape')e.preventDefault();return;}if(e.key==='Escape'&&!document.querySelector('dialog[open]')){if(DEV&&!$('.workspace').classList.contains('console-closed')){$('#console-toggle').click();return;}menu($('#pause-menu').hidden);}if(e.key.toLowerCase()==='j'&&!e.repeat){menu(true);document.querySelector<HTMLDialogElement>('#guide-dialog')!.showModal();}});
window.addEventListener('pagehide',()=>{stream?.close();ambience.dispose();},{once:true});

$('#tutorial-continue').onclick=()=>game.resumeTutorial();$('#tutorial-practice-skip').onclick=()=>game.resumeTutorial(false);$('#tutorial-skip').onclick=()=>game.skipTutorial();

function audioStatus(status:string){return t(status==='ready'?'audio.ready':status==='loading'?'audio.loading':status==='failed'?'audio.failed':status==='off'?'settings.soundOff':'audio.waiting');}
function turnPage(){renderStages();const book=$('.patrol-book');book.classList.remove('turning');void book.offsetWidth;book.classList.add('turning');}
function applyMenuLanguage(){
 setLocale(getLocale());document.documentElement.lang=getLocale();document.title='夜勤病棟';
 const labels:Record<string,MessageKey>={'.desk-kicker':'menu.hospital','.desk-title p':'menu.subtitle','.book-header>span:first-child':'menu.book','.index-label':'menu.index','.survey-frame>span':'menu.sketch','.desk-footnote>span:first-child':'menu.warning','#desk-settings':'menu.settings','#book-guide':'menu.guide','#language-label':'menu.language','#pause-menu h2':'settings.title','#resume':'settings.resume','#guide':'settings.guide','#volume-label':'settings.volume','#fullscreen':'settings.fullscreen','#menu-stages':'settings.stages','#guide-dialog h2':'guide.title','#close-guide':'guide.close'};
 for(const [selector,key] of Object.entries(labels))$(selector).textContent=t(key);
 $('#stage-prev').setAttribute('aria-label',t('menu.previous'));$('#stage-next').setAttribute('aria-label',t('menu.next'));$('.patrol-book').setAttribute('aria-label',t('menu.book'));$('#pause-menu').setAttribute('aria-label',t('settings.title'));
 $('.monitor-caption').textContent=t('menu.desk');
 document.querySelectorAll('#guide-dialog p').forEach((el,i)=>el.textContent=t(('guide.'+(i+1)) as MessageKey));
 $('#sound').textContent=t(audioOn?'settings.soundOn':'settings.soundOff');$('#music-status').textContent=audioStatus($('#music-status').dataset.status??'');ambience.onTrack(currentTrack,currentChase);
 (document.querySelector('#menu-language') as HTMLSelectElement).value=getLocale();renderStages();
}
$('#menu-language').onchange=async()=>{setLocale((document.querySelector('#menu-language') as HTMLSelectElement).value,true);sessionStorage.setItem('night-shift-session-language',document.body.dataset.liveSession??'');try{await flushSave();window.location.reload();}catch{toast(msg('desktop.saveError'));}};

if(DEV){
 const box=document.createElement('div');box.id='gift-test-controls';box.style.cssText='display:flex;flex-wrap:wrap;gap:5px;margin-top:10px';
 for(const [id,d] of Object.entries(giftDefinitions)){const b=document.createElement('button');b.dataset.gift=id;b.textContent=t(`gift.${d.kind}`);b.onclick=()=>{const scene=(window as unknown as {__nightshift:()=>{gifts:{runId:string}}}).__nightshift();game.gift({id:crypto.randomUUID(),runId:scene.gifts.runId,giftId:id as GiftEvent['giftId'],viewer:msg('ui.test-viewer'),userId:'local-test',count:1});};box.append(b);}
 document.querySelector('#console-toggle')?.parentElement?.append(box);
 const update=()=>{box.hidden=document.querySelector('.workspace')!.classList.contains('console-closed');};document.querySelector('#console-toggle')?.addEventListener('click',update);update();
}

connectDesktop(game);

window.addEventListener('nightshift:save-error',()=>{game.setPaused(true);toast(msg('desktop.saveError'));});
